import type { PlanEvent, RaceInfo, Session } from '../plan-types'

export const RACE_INFO: RaceInfo = {
  "name": "Trail 33km",
  "date": "2026-06-21",
  "distance": "33km",
  "elevation": "2130D+"
}

export const EVENTS: PlanEvent[] = [
  {
    "date": "2026-04-18",
    "label": "WC Trail Avril",
    "emoji": "🏔",
    "target": "Weekend choc montagne"
  },
  {
    "date": "2026-05-16",
    "label": "WC Trail Mai",
    "emoji": "🏔",
    "target": "Weekend choc montagne"
  },
  {
    "date": "2026-05-30",
    "label": "Rando 80km",
    "emoji": "⛰️",
    "target": "80km – 2 jours"
  },
  {
    "date": "2026-06-13",
    "label": "WC Trail Juin",
    "emoji": "🏔",
    "target": "Weekend choc début juin"
  },
  {
    "date": "2026-06-21",
    "label": "COURSE 33km",
    "emoji": "🏆",
    "target": "33km / 2130D+"
  }
]

export const PLAN: Session[] = [
  {
    "id": "s-L-2026-03-23",
    "phase": 1,
    "phaseLabel": "Base endurance + introduction trail",
    "week": 1,
    "weekLabel": "23 – 29 mar",
    "date": "2026-03-23",
    "day": "Lun",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": "Mise en route"
  },
  {
    "id": "s-L-2026-03-24",
    "phase": 1,
    "week": 1,
    "date": "2026-03-24",
    "day": "Mar",
    "type": "EF",
    "content": "Footing EF route 35' — prise de repères, allure très confortable 6:00/km, foulée relâchée",
    "km": 6,
    "dp": null,
    "note": "Première séance du plan — juste mettre les jambes en route"
  },
  {
    "id": "s-L-2026-03-25",
    "phase": 1,
    "week": 1,
    "date": "2026-03-25",
    "day": "Mer",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-03-26",
    "phase": 1,
    "week": 1,
    "date": "2026-03-26",
    "day": "Jeu",
    "type": "RENFO",
    "content": "Activation 10' (cercles hanches, squats aeriens, fentes lat.) | Renfo jambes 30' — bilan musculaire de départ : squats, fentes, mollets, gainage planche 3×30'' | RAC 8' etirements statiques (mollets, quadris, ischio, fessiers)",
    "km": null,
    "dp": null,
    "note": "Identifier les points faibles dès le début"
  },
  {
    "id": "s-L-2026-03-27",
    "phase": 1,
    "week": 1,
    "date": "2026-03-27",
    "day": "Ven",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-03-28",
    "phase": 1,
    "week": 1,
    "date": "2026-03-28",
    "day": "Sam",
    "type": "TRAIL",
    "content": "Trail intro 1h — terrain facile, EF strict, marcher toutes les montées, découvrir les sensations",
    "km": 10,
    "dp": 300,
    "note": "Pas de chrono — évaluer les sensations terrain"
  },
  {
    "id": "s-L-2026-03-29",
    "phase": 1,
    "week": 1,
    "date": "2026-03-29",
    "day": "Dim",
    "type": "EF",
    "content": "Footing récup route 25' — très lent",
    "km": 4,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-03-30",
    "phase": 1,
    "week": 2,
    "weekLabel": "30 mar – 5 avr",
    "date": "2026-03-30",
    "day": "Lun",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-03-31",
    "phase": 1,
    "week": 2,
    "date": "2026-03-31",
    "day": "Mar",
    "type": "EF",
    "content": "Footing EF route 40' — allure confortable 5:30–6:00/km, foulée relâchée",
    "km": 7,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-04-01",
    "phase": 1,
    "week": 2,
    "date": "2026-04-01",
    "day": "Mer",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-04-02",
    "phase": 1,
    "week": 2,
    "date": "2026-04-02",
    "day": "Jeu",
    "type": "RENFO",
    "content": "Activation 10' (cercles hanches, squats aeriens, fentes lat.) | Renfo jambes 35' — squats, fentes avant/arrière, mollets debout/assis, step-up, gainage planche 3×45'' | RAC 8' etirements statiques (mollets, quadris, ischio, fessiers)",
    "km": null,
    "dp": null,
    "note": "1× renfo/sem"
  },
  {
    "id": "s-L-2026-04-03",
    "phase": 1,
    "week": 2,
    "date": "2026-04-03",
    "day": "Ven",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-04-04",
    "phase": 1,
    "week": 2,
    "date": "2026-04-04",
    "day": "Sam",
    "type": "TRAIL",
    "content": "Trail intro montagne 1h15 — EF strict, marcher toutes les montées >8%, terrain varié",
    "km": 12,
    "dp": 400,
    "note": "Priorité sensation terrain, pas chrono"
  },
  {
    "id": "s-L-2026-04-05",
    "phase": 1,
    "week": 2,
    "date": "2026-04-05",
    "day": "Dim",
    "type": "EF",
    "content": "Footing récup route 30'",
    "km": 5,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-04-06",
    "phase": 1,
    "week": 3,
    "weekLabel": "6 – 12 avr",
    "date": "2026-04-06",
    "day": "Lun",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-04-07",
    "phase": 1,
    "week": 3,
    "date": "2026-04-07",
    "day": "Mar",
    "type": "VMA",
    "content": "Ech 15'@6:35/km + 4 strides 80m@4:30/km | 6x3'@4:30/km — recup 2'@6:55/km | RAC 10'@6:55/km",
    "km": 12,
    "dp": null,
    "note": "Ne pas partir trop vite sur le 1er intervalle"
  },
  {
    "id": "s-L-2026-04-08",
    "phase": 1,
    "week": 3,
    "date": "2026-04-08",
    "day": "Mer",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-04-09",
    "phase": 1,
    "week": 3,
    "date": "2026-04-09",
    "day": "Jeu",
    "type": "RENFO",
    "content": "Activation 10' (cercles hanches, squats aeriens, fentes lat.) | Renfo + escaliers 40' — 3×20 squats sautés, 3×15 fentes bulgares, 3×20 mollets, escalier 10' continu | RAC 8' etirements statiques (mollets, quadris, ischio, fessiers)",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-04-10",
    "phase": 1,
    "week": 3,
    "date": "2026-04-10",
    "day": "Ven",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-04-11",
    "phase": 1,
    "week": 3,
    "date": "2026-04-11",
    "day": "Sam",
    "type": "TRAIL",
    "content": "Ech 10' marche active@6:55/km | Trail technique 1h30 — alterné run/marche montée, focus descente relâchée@6:55/km — monter >8% en marche | RAC 10' marche@6:55/km",
    "km": 15,
    "dp": 550,
    "note": "Travailler foulée descente — courte, sous le centre de gravité"
  },
  {
    "id": "s-L-2026-04-12",
    "phase": 1,
    "week": 3,
    "date": "2026-04-12",
    "day": "Dim",
    "type": "EF",
    "content": "Footing récup route 35'",
    "km": 6,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-04-13",
    "phase": 1,
    "week": 4,
    "weekLabel": "13 – 17 avr",
    "date": "2026-04-13",
    "day": "Lun",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": "🏔 WC TRAIL SAM–DIM 18–19/04"
  },
  {
    "id": "s-L-2026-04-14",
    "phase": 1,
    "week": 4,
    "date": "2026-04-14",
    "day": "Mar",
    "type": "TEMPO",
    "content": "Ech 15'@6:35/km | 3x10'@4:57/km — recup 3'@5:45/km | RAC 10'@6:55/km",
    "km": 13,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-04-15",
    "phase": 1,
    "week": 4,
    "date": "2026-04-15",
    "day": "Mer",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-04-16",
    "phase": 1,
    "week": 4,
    "date": "2026-04-16",
    "day": "Jeu",
    "type": "RENFO",
    "content": "Activation 10' (cercles hanches, squats aeriens, fentes lat.) | Renfo léger 25' — fentes, mollets, gainage. Pas d'effort max — WC demain | RAC 8' etirements statiques (mollets, quadris, ischio, fessiers)",
    "km": null,
    "dp": null,
    "note": "Garder les jambes pour le WC"
  },
  {
    "id": "s-L-2026-04-17",
    "phase": 1,
    "week": 4,
    "date": "2026-04-17",
    "day": "Ven",
    "type": "REPOS",
    "content": "Prépa WC — logistique, nutrition",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-04-18",
    "phase": 2,
    "phaseLabel": "Montée en charge + Weekend Choc Avril",
    "week": 4,
    "weekLabel": "WC Avril 18–19 avr",
    "date": "2026-04-18",
    "day": "Sam",
    "type": "WC",
    "content": "Ech 10' marche@6:55/km | 🏔 WC Avril J1 — Trail montagne 20–22km / 1200D+ — EF strict montée, marcher si >8%, bâtons ok@6:55/km | RAC 10' marche@6:55/km",
    "km": 21,
    "dp": 1200,
    "note": "Alimentation 1×/h dès le départ. EF strict.",
    "isEvent": true
  },
  {
    "id": "s-L-2026-04-19",
    "phase": 2,
    "week": 4,
    "date": "2026-04-19",
    "day": "Dim",
    "type": "WC",
    "content": "Ech 10' marche@6:55/km | 🏔 WC Avril J2 — Trail 15–18km / 900D+ — même terrain, travail descente technique@6:55/km | RAC 10' marche@6:55/km",
    "km": 16,
    "dp": 900,
    "note": "Nutrition dès le matin. Récup active en descente."
  },
  {
    "id": "s-L-2026-04-20",
    "phase": 2,
    "week": 5,
    "weekLabel": "20 – 26 avr",
    "date": "2026-04-20",
    "day": "Lun",
    "type": "REPOS",
    "content": "Récup WC — marche OK, pas de course",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-04-21",
    "phase": 2,
    "week": 5,
    "date": "2026-04-21",
    "day": "Mar",
    "type": "EF",
    "content": "Footing récup route 30' — très lent, écoute du corps",
    "km": 5,
    "dp": null,
    "note": "Si jambes lourdes : repos"
  },
  {
    "id": "s-L-2026-04-22",
    "phase": 2,
    "week": 5,
    "date": "2026-04-22",
    "day": "Mer",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-04-23",
    "phase": 2,
    "week": 5,
    "date": "2026-04-23",
    "day": "Jeu",
    "type": "RENFO",
    "content": "Activation 10' (cercles hanches, squats aeriens, fentes lat.) | Renfo excentrique 40' — nordic hamstring 3×6, step-down 3×12, fentes sautées 3×10, gainage latéral 2×45'' | RAC 8' etirements statiques (mollets, quadris, ischio, fessiers)",
    "km": null,
    "dp": null,
    "note": "Reprend charge renfo après récup WC"
  },
  {
    "id": "s-L-2026-04-24",
    "phase": 2,
    "week": 5,
    "date": "2026-04-24",
    "day": "Ven",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-04-25",
    "phase": 2,
    "week": 5,
    "date": "2026-04-25",
    "day": "Sam",
    "type": "TRAIL",
    "content": "Ech 10' marche active@6:55/km | Trail EF 1h30 — terrain mixte, reprise progressive post-WC@6:55/km — monter >8% en marche | RAC 10' marche@6:55/km",
    "km": 15,
    "dp": 500,
    "note": ""
  },
  {
    "id": "s-L-2026-04-26",
    "phase": 2,
    "week": 5,
    "date": "2026-04-26",
    "day": "Dim",
    "type": "EF",
    "content": "Footing route 40'",
    "km": 7,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-04-27",
    "phase": 2,
    "week": 6,
    "weekLabel": "27 avr – 3 mai",
    "date": "2026-04-27",
    "day": "Lun",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-04-28",
    "phase": 2,
    "week": 6,
    "date": "2026-04-28",
    "day": "Mar",
    "type": "VMA",
    "content": "Ech 15'@6:35/km + 4 strides 80m@4:30/km | 8x2'@4:30/km — recup 1'30''@6:55/km | RAC 10'@6:55/km",
    "km": 13,
    "dp": null,
    "note": "Conserver la même allure sur tous les intervals"
  },
  {
    "id": "s-L-2026-04-29",
    "phase": 2,
    "week": 6,
    "date": "2026-04-29",
    "day": "Mer",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-04-30",
    "phase": 2,
    "week": 6,
    "date": "2026-04-30",
    "day": "Jeu",
    "type": "RENFO",
    "content": "Activation 10' (cercles hanches, squats aeriens, fentes lat.) | Renfo + escalier 45' — 4×10 squats explosifs, escalier 15' continu, 3×15 fentes bulgares, 3×20 mollets lestés, gainage 3×1' | RAC 8' etirements statiques (mollets, quadris, ischio, fessiers)",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-05-01",
    "phase": 2,
    "week": 6,
    "date": "2026-05-01",
    "day": "Ven",
    "type": "REPOS",
    "content": "Férié — repos actif, marche",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-05-02",
    "phase": 2,
    "week": 6,
    "date": "2026-05-02",
    "day": "Sam",
    "type": "TRAIL",
    "content": "Ech 10' marche active@6:55/km | Trail long 2h — sortie longue EF, simuler effort course : marche montée / run plat-descente@6:55/km — monter >8% en marche | RAC 10' marche@6:55/km",
    "km": 19,
    "dp": 700,
    "note": "Alimentation toutes les 45min."
  },
  {
    "id": "s-L-2026-05-03",
    "phase": 2,
    "week": 6,
    "date": "2026-05-03",
    "day": "Dim",
    "type": "EF",
    "content": "Footing route 40' récup",
    "km": 7,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-05-04",
    "phase": 3,
    "phaseLabel": "Spécificité montagne + WC Mai + Rando 80km",
    "week": 7,
    "weekLabel": "4 – 10 mai",
    "date": "2026-05-04",
    "day": "Lun",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-05-05",
    "phase": 3,
    "week": 7,
    "date": "2026-05-05",
    "day": "Mar",
    "type": "TEMPO",
    "content": "Ech 15'@6:35/km | 4x6'@4:57/km — recup 3'@5:45/km | RAC 10'@6:55/km",
    "km": 13,
    "dp": null,
    "note": "Trouver une côte à 4–6% sur route"
  },
  {
    "id": "s-L-2026-05-06",
    "phase": 3,
    "week": 7,
    "date": "2026-05-06",
    "day": "Mer",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-05-07",
    "phase": 3,
    "week": 7,
    "date": "2026-05-07",
    "day": "Jeu",
    "type": "RENFO",
    "content": "Activation 10' (cercles hanches, squats aeriens, fentes lat.) | Renfo spécifique descente 40' — step-down excentrique 4×15, fentes bulgares 4×12, proprioception 1 jambe 3×30'', gainage anti-rotation | RAC 8' etirements statiques (mollets, quadris, ischio, fessiers)",
    "km": null,
    "dp": null,
    "note": "Focus stabilisation cheville et genou"
  },
  {
    "id": "s-L-2026-05-08",
    "phase": 3,
    "week": 7,
    "date": "2026-05-08",
    "day": "Ven",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-05-09",
    "phase": 3,
    "week": 7,
    "date": "2026-05-09",
    "day": "Sam",
    "type": "TRAIL",
    "content": "Ech 10' marche active@6:55/km | Trail montagne 2h — D+ progressif, simulation allure course 5:30–6:00/km GAP@6:55/km — monter >8% en marche | RAC 10' marche@6:55/km",
    "km": 18,
    "dp": 900,
    "note": "GAP = pace ajusté au dénivelé. Monter à allure effort stable."
  },
  {
    "id": "s-L-2026-05-10",
    "phase": 3,
    "week": 7,
    "date": "2026-05-10",
    "day": "Dim",
    "type": "EF",
    "content": "Footing route 35' — récup passive dimanche",
    "km": 6,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-05-11",
    "phase": 3,
    "week": 8,
    "weekLabel": "11 – 15 mai",
    "date": "2026-05-11",
    "day": "Lun",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": "🏔 WC TRAIL SAM–DIM 16–17/05"
  },
  {
    "id": "s-L-2026-05-12",
    "phase": 3,
    "week": 8,
    "date": "2026-05-12",
    "day": "Mar",
    "type": "VMA",
    "content": "Ech 15'@6:35/km + 4 strides 80m@4:30/km | 5x4'@4:30/km — recup 2'@6:55/km | RAC 10'@6:55/km",
    "km": 13,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-05-13",
    "phase": 3,
    "week": 8,
    "date": "2026-05-13",
    "day": "Mer",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-05-14",
    "phase": 3,
    "week": 8,
    "date": "2026-05-14",
    "day": "Jeu",
    "type": "RENFO",
    "content": "Activation 10' (cercles hanches, squats aeriens, fentes lat.) | Renfo léger 25' avant WC — mollets, fentes légères, gainage. Volume réduit. | RAC 8' etirements statiques (mollets, quadris, ischio, fessiers)",
    "km": null,
    "dp": null,
    "note": "Garder les jambes fraîches pour le WC"
  },
  {
    "id": "s-L-2026-05-15",
    "phase": 3,
    "week": 8,
    "date": "2026-05-15",
    "day": "Ven",
    "type": "REPOS",
    "content": "Prépa WC — logistique, nutrition, sommeil",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-05-16",
    "phase": 3,
    "week": 8,
    "weekLabel": "WC Mai 16–17 mai",
    "date": "2026-05-16",
    "day": "Sam",
    "type": "WC",
    "content": "Ech 10' marche@6:55/km | 🏔 WC Mai J1 — Trail montagne 22–24km / 1400D+ — simulation course : départ contrôlé, allure EF montée, descente technique@6:55/km | RAC 10' marche@6:55/km",
    "km": 23,
    "dp": 1400,
    "note": "Objectif : tenir allure identique début et fin. Gel toutes les 45min.",
    "isEvent": true
  },
  {
    "id": "s-L-2026-05-17",
    "phase": 3,
    "week": 8,
    "date": "2026-05-17",
    "day": "Dim",
    "type": "WC",
    "content": "Ech 10' marche@6:55/km | 🏔 WC Mai J2 — Trail 14–16km / 800D+ — récup terrain, travail descente longue@6:55/km | RAC 10' marche@6:55/km",
    "km": 15,
    "dp": 800,
    "note": ""
  },
  {
    "id": "s-L-2026-05-18",
    "phase": 3,
    "week": 9,
    "weekLabel": "18 – 22 mai",
    "date": "2026-05-18",
    "day": "Lun",
    "type": "REPOS",
    "content": "Récup WC — marche, étirements",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-05-19",
    "phase": 3,
    "week": 9,
    "date": "2026-05-19",
    "day": "Mar",
    "type": "EF",
    "content": "Footing route 35' — très léger post-WC",
    "km": 6,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-05-20",
    "phase": 3,
    "week": 9,
    "date": "2026-05-20",
    "day": "Mer",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-05-21",
    "phase": 3,
    "week": 9,
    "date": "2026-05-21",
    "day": "Jeu",
    "type": "RENFO",
    "content": "Activation 10' (cercles hanches, squats aeriens, fentes lat.) | Renfo modéré 35' — mollets, quadris, gainage. Pas d'explosif. Prépa rando. | RAC 8' etirements statiques (mollets, quadris, ischio, fessiers)",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-05-22",
    "phase": 3,
    "week": 9,
    "date": "2026-05-22",
    "day": "Ven",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-05-23",
    "phase": 3,
    "week": 9,
    "date": "2026-05-23",
    "day": "Sam",
    "type": "TRAIL",
    "content": "Trail EF 1h20 — terrain roulant, relance progressive",
    "km": 13,
    "dp": 400,
    "note": ""
  },
  {
    "id": "s-L-2026-05-24",
    "phase": 3,
    "week": 9,
    "date": "2026-05-24",
    "day": "Dim",
    "type": "REPOS",
    "content": "Repos / prépa logistique rando 80km",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-05-25",
    "phase": 3,
    "week": 10,
    "weekLabel": "25–29 mai",
    "date": "2026-05-25",
    "day": "Lun",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": "⛰️ RANDO 80km SAM–DIM 30–31 mai"
  },
  {
    "id": "s-L-2026-05-26",
    "phase": 3,
    "week": 10,
    "date": "2026-05-26",
    "day": "Mar",
    "type": "EF",
    "content": "Footing route léger 30' — jambes légères, aucune intensité",
    "km": 5,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-05-27",
    "phase": 3,
    "week": 10,
    "date": "2026-05-27",
    "day": "Mer",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-05-28",
    "phase": 3,
    "week": 10,
    "date": "2026-05-28",
    "day": "Jeu",
    "type": "RENFO",
    "content": "Activation 10' (cercles hanches, squats aeriens, fentes lat.) | Renfo minimal 20' — activation mollets, fentes légères, gainage. Rien d'intensif avant rando. | RAC 8' etirements statiques (mollets, quadris, ischio, fessiers)",
    "km": null,
    "dp": null,
    "note": "Volume très réduit"
  },
  {
    "id": "s-L-2026-05-29",
    "phase": 3,
    "week": 10,
    "date": "2026-05-29",
    "day": "Ven",
    "type": "REPOS",
    "content": "Voyage / prépa rando — nutrition, matériel, bâtons",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-05-30",
    "phase": 3,
    "week": 10,
    "date": "2026-05-30",
    "day": "Sam",
    "type": "RANDO",
    "content": "⛰️ Rando 80km J1 — ~40km, marche active en montée, bâtons, alimentation toutes les 45min",
    "km": 40,
    "dp": 2500,
    "note": "EF strict. Pas de course. Gérer énergie sur 2 jours.",
    "isEvent": true
  },
  {
    "id": "s-L-2026-05-31",
    "phase": 3,
    "week": 10,
    "date": "2026-05-31",
    "day": "Dim",
    "type": "RANDO",
    "content": "⛰️ Rando 80km J2 — ~40km, même gestion, nutrition renforcée, finir propre",
    "km": 40,
    "dp": 2500,
    "note": "Rester régulier. Arrêter si douleur genou/cheville."
  },
  {
    "id": "s-L-2026-06-01",
    "phase": 4,
    "phaseLabel": "Dernier bloc + WC Juin + Affûtage",
    "week": 11,
    "weekLabel": "1 – 7 juin",
    "date": "2026-06-01",
    "day": "Lun",
    "type": "REPOS",
    "content": "J+1 Rando — repos complet",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-06-02",
    "phase": 4,
    "week": 11,
    "date": "2026-06-02",
    "day": "Mar",
    "type": "EF",
    "content": "Marche/footing 25' — bilan musculaire. Si douleurs : repos total.",
    "km": 4,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-06-03",
    "phase": 4,
    "week": 11,
    "date": "2026-06-03",
    "day": "Mer",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-06-04",
    "phase": 4,
    "week": 11,
    "date": "2026-06-04",
    "day": "Jeu",
    "type": "RENFO",
    "content": "Activation 10' (cercles hanches, squats aeriens, fentes lat.) | Renfo relance 30' — mollets, step-down, gainage. Léger, réveil musculaire. | RAC 8' etirements statiques (mollets, quadris, ischio, fessiers)",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-06-05",
    "phase": 4,
    "week": 11,
    "date": "2026-06-05",
    "day": "Ven",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-06-06",
    "phase": 4,
    "week": 11,
    "date": "2026-06-06",
    "day": "Sam",
    "type": "TRAIL",
    "content": "Trail EF relance 1h — terrain varié, allure confortable, tester les jambes post-rando",
    "km": 12,
    "dp": 450,
    "note": ""
  },
  {
    "id": "s-L-2026-06-07",
    "phase": 4,
    "week": 11,
    "date": "2026-06-07",
    "day": "Dim",
    "type": "EF",
    "content": "Footing route 35' — récup active",
    "km": 6,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-06-08",
    "phase": 4,
    "week": 12,
    "weekLabel": "8 – 12 juin",
    "date": "2026-06-08",
    "day": "Lun",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": "🏔 WC TRAIL SAM–DIM 13–14/06"
  },
  {
    "id": "s-L-2026-06-09",
    "phase": 4,
    "week": 12,
    "date": "2026-06-09",
    "day": "Mar",
    "type": "TEMPO",
    "content": "Ech 15'@6:35/km | 2x15'@4:57/km — recup 4'@5:45/km | RAC 10'@6:55/km",
    "km": 14,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-06-10",
    "phase": 4,
    "week": 12,
    "date": "2026-06-10",
    "day": "Mer",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-06-11",
    "phase": 4,
    "week": 12,
    "date": "2026-06-11",
    "day": "Jeu",
    "type": "RENFO",
    "content": "Activation 10' (cercles hanches, squats aeriens, fentes lat.) | Renfo léger 20' — activation uniquement. Fentes, mollets, gainage. Avant WC. | RAC 8' etirements statiques (mollets, quadris, ischio, fessiers)",
    "km": null,
    "dp": null,
    "note": "Dernier renfo avant la course"
  },
  {
    "id": "s-L-2026-06-12",
    "phase": 4,
    "week": 12,
    "date": "2026-06-12",
    "day": "Ven",
    "type": "REPOS",
    "content": "Repos — prépa logistique WC",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-06-13",
    "phase": 4,
    "week": 12,
    "weekLabel": "WC Juin 13–14 juin",
    "date": "2026-06-13",
    "day": "Sam",
    "type": "WC",
    "content": "Ech 10' marche@6:55/km | 🏔 WC Juin J1 — Trail 18–20km / 1100D+ — simulation race day : ravito, nutrition, équipement course@6:55/km | RAC 10' marche@6:55/km",
    "km": 19,
    "dp": 1100,
    "note": "Tester équipement et chaussures de course. Alimentation identique à J-course.",
    "isEvent": true
  },
  {
    "id": "s-L-2026-06-14",
    "phase": 4,
    "week": 12,
    "date": "2026-06-14",
    "day": "Dim",
    "type": "EF",
    "content": "Ech 10'@6:35/km | Trail récup 1h — terrain facile, EF strict, évaluation sensations@5:45/km | RAC 10'@6:55/km",
    "km": 10,
    "dp": 300,
    "note": ""
  },
  {
    "id": "s-L-2026-06-15",
    "phase": 5,
    "phaseLabel": "Affûtage final — Fraîcheur maximale",
    "week": 13,
    "weekLabel": "15 – 21 juin",
    "date": "2026-06-15",
    "day": "Lun",
    "type": "REPOS",
    "content": "J+1 WC — récup",
    "km": null,
    "dp": null,
    "note": "🏆 COURSE DIM 21/06 — Volume ↘ 50%"
  },
  {
    "id": "s-L-2026-06-16",
    "phase": 5,
    "week": 13,
    "date": "2026-06-16",
    "day": "Mar",
    "type": "EF",
    "content": "Footing route 25' + 4 strides 100m — activation, jambes légères",
    "km": 5,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-06-17",
    "phase": 5,
    "week": 13,
    "date": "2026-06-17",
    "day": "Mer",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-06-18",
    "phase": 5,
    "week": 13,
    "date": "2026-06-18",
    "day": "Jeu",
    "type": "EF",
    "content": "Footing route 20' — très léger, aucune intensité",
    "km": 3,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-06-19",
    "phase": 5,
    "week": 13,
    "date": "2026-06-19",
    "day": "Ven",
    "type": "REPOS",
    "content": "Repos total — nutrition glucidique, hydratation++, sommeil tôt",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-L-2026-06-20",
    "phase": 5,
    "week": 13,
    "date": "2026-06-20",
    "day": "Sam",
    "type": "REPOS",
    "content": "Veille course — 10min marche légère, étirements doux. Préparer dossard et matériel.",
    "km": null,
    "dp": null,
    "note": "Dormir tôt. Petit-déj race = identique à celui testé en WC."
  },
  {
    "id": "s-L-2026-06-21",
    "phase": 5,
    "week": 13,
    "date": "2026-06-21",
    "day": "Dim",
    "type": "RACE",
    "content": "Ech 20'@6:35/km + 4 strides 100m | 🏆 COURSE 33km / 2130D+ — Départ contrôlé 1ers 5km, marcher montées >10%, gérer ravitos, accélérer si possible dernier 5km@6:55/km | RAC 15' marche@6:55/km",
    "km": 36,
    "dp": 2130,
    "note": "🏆 OBJECTIF — allure cible 6:30–7:00/km GAP. Gel toutes les 45min.",
    "isEvent": true
  },
  {
    "id": "s-L-2026-06-22",
    "phase": 5,
    "week": 13,
    "date": "2026-06-22",
    "day": "Lun",
    "type": "REPOS",
    "content": "Récup post-course 🎉",
    "km": null,
    "dp": null,
    "note": ""
  }
]
