import type { PlanEvent, RaceInfo, Session } from '../plan-types'

export const RACE_INFO: RaceInfo = {
  "name": "Trail 18km",
  "date": "2026-06-21",
  "distance": "18km",
  "elevation": "1000D+"
}

export const EVENTS: PlanEvent[] = [
  {
    "date": "2026-05-09",
    "label": "WC Trail Mai",
    "emoji": "🏔",
    "target": "Weekend choc trail"
  },
  {
    "date": "2026-06-21",
    "label": "COURSE 18km",
    "emoji": "🏆",
    "target": "18km / 1000D+"
  }
]

export const PLAN: Session[] = [
  {
    "id": "s-T-2026-03-23",
    "phase": 1,
    "phaseLabel": "Mise en route — 2 séances/semaine",
    "week": 1,
    "weekLabel": "23 – 29 mar",
    "date": "2026-03-23",
    "day": "Lun",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-03-24",
    "phase": 1,
    "week": 1,
    "date": "2026-03-24",
    "day": "Mar",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-03-25",
    "phase": 1,
    "week": 1,
    "date": "2026-03-25",
    "day": "Mer",
    "type": "EF",
    "content": "Ech 10'@5:45/km | Footing EF route 35' — allure confortable, foulée relâchée@5:45/km | RAC 10'@5:45/km",
    "km": 9,
    "dp": null,
    "note": "Première séance — pas d'objectif de vitesse"
  },
  {
    "id": "s-T-2026-03-26",
    "phase": 1,
    "week": 1,
    "date": "2026-03-26",
    "day": "Jeu",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-03-27",
    "phase": 1,
    "week": 1,
    "date": "2026-03-27",
    "day": "Ven",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-03-28",
    "phase": 1,
    "week": 1,
    "date": "2026-03-28",
    "day": "Sam",
    "type": "TRAIL",
    "content": "Sortie trail ou route vallonnée 45' — EF strict, explorer le terrain, marcher les montées",
    "km": 8,
    "dp": 200,
    "note": "Pas de chrono — évaluer les sensations"
  },
  {
    "id": "s-T-2026-03-29",
    "phase": 1,
    "week": 1,
    "date": "2026-03-29",
    "day": "Dim",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-03-30",
    "phase": 1,
    "week": 2,
    "weekLabel": "30 mar – 5 avr",
    "date": "2026-03-30",
    "day": "Lun",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-03-31",
    "phase": 1,
    "week": 2,
    "date": "2026-03-31",
    "day": "Mar",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-04-01",
    "phase": 1,
    "week": 2,
    "date": "2026-04-01",
    "day": "Mer",
    "type": "EF",
    "content": "Ech 10'@5:45/km | Footing EF route 40' — allure régulière, respiration confortable@5:45/km | RAC 10'@5:45/km",
    "km": 10,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-04-02",
    "phase": 1,
    "week": 2,
    "date": "2026-04-02",
    "day": "Jeu",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-04-03",
    "phase": 1,
    "week": 2,
    "date": "2026-04-03",
    "day": "Ven",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-04-04",
    "phase": 1,
    "week": 2,
    "date": "2026-04-04",
    "day": "Sam",
    "type": "TRAIL",
    "content": "Sortie trail 1h — terrain varié, alterner run plat et marche en montée, focus placement pied",
    "km": 10,
    "dp": 300,
    "note": "Marcher toutes les montées >8% — économie d'énergie"
  },
  {
    "id": "s-T-2026-04-05",
    "phase": 1,
    "week": 2,
    "date": "2026-04-05",
    "day": "Dim",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-04-06",
    "phase": 1,
    "week": 3,
    "weekLabel": "6 – 12 avr",
    "date": "2026-04-06",
    "day": "Lun",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-04-07",
    "phase": 1,
    "week": 3,
    "date": "2026-04-07",
    "day": "Mar",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-04-08",
    "phase": 1,
    "week": 3,
    "date": "2026-04-08",
    "day": "Mer",
    "type": "TEMPO",
    "content": "Ech 15'@5:45/km | 2x10'@4:45/km — recup 3'@5:45/km | RAC 10'@5:45/km",
    "km": 9,
    "dp": null,
    "note": "Premier travail tempo — rester régulière sur les 2 blocs"
  },
  {
    "id": "s-T-2026-04-09",
    "phase": 1,
    "week": 3,
    "date": "2026-04-09",
    "day": "Jeu",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-04-10",
    "phase": 1,
    "week": 3,
    "date": "2026-04-10",
    "day": "Ven",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-04-11",
    "phase": 1,
    "week": 3,
    "date": "2026-04-11",
    "day": "Sam",
    "type": "TRAIL",
    "content": "Sortie trail 1h15 — D+ progressif, travailler la montée active (marche rapide bras actifs)",
    "km": 12,
    "dp": 400,
    "note": "Technique montée : bras qui poussent sur les cuisses"
  },
  {
    "id": "s-T-2026-04-12",
    "phase": 1,
    "week": 3,
    "date": "2026-04-12",
    "day": "Dim",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-04-13",
    "phase": 1,
    "week": 4,
    "weekLabel": "13 – 19 avr",
    "date": "2026-04-13",
    "day": "Lun",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-04-14",
    "phase": 1,
    "week": 4,
    "date": "2026-04-14",
    "day": "Mar",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-04-15",
    "phase": 1,
    "week": 4,
    "date": "2026-04-15",
    "day": "Mer",
    "type": "EF",
    "content": "Ech 10'@5:45/km | Footing EF route 45' — allure stable@5:45/km | RAC 10'@5:45/km",
    "km": 11,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-04-16",
    "phase": 1,
    "week": 4,
    "date": "2026-04-16",
    "day": "Jeu",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-04-17",
    "phase": 1,
    "week": 4,
    "date": "2026-04-17",
    "day": "Ven",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-04-18",
    "phase": 1,
    "week": 4,
    "date": "2026-04-18",
    "day": "Sam",
    "type": "TRAIL",
    "content": "Sortie trail 1h30 — EF, première sortie longue, test ravitaillement (eau, barre)",
    "km": 14,
    "dp": 450,
    "note": "Tester hydratation et alimentation sur une sortie longue"
  },
  {
    "id": "s-T-2026-04-19",
    "phase": 1,
    "week": 4,
    "date": "2026-04-19",
    "day": "Dim",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-04-20",
    "phase": 2,
    "phaseLabel": "Montée en charge — passage à 3 séances/semaine",
    "week": 5,
    "weekLabel": "20 – 26 avr",
    "date": "2026-04-20",
    "day": "Lun",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-04-21",
    "phase": 2,
    "week": 5,
    "date": "2026-04-21",
    "day": "Mar",
    "type": "EF",
    "content": "Ech 10'@5:45/km | Footing EF route 35'@5:45/km | RAC 10'@5:45/km",
    "km": 9,
    "dp": null,
    "note": "3ème séance ajoutée — rester légère"
  },
  {
    "id": "s-T-2026-04-22",
    "phase": 2,
    "week": 5,
    "date": "2026-04-22",
    "day": "Mer",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-04-23",
    "phase": 2,
    "week": 5,
    "date": "2026-04-23",
    "day": "Jeu",
    "type": "TEMPO",
    "content": "Ech 15'@5:45/km | 3x8'@4:45/km — recup 3'@5:45/km | RAC 10'@5:45/km",
    "km": 10,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-04-24",
    "phase": 2,
    "week": 5,
    "date": "2026-04-24",
    "day": "Ven",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-04-25",
    "phase": 2,
    "week": 5,
    "date": "2026-04-25",
    "day": "Sam",
    "type": "TRAIL",
    "content": "Sortie trail 1h30 — travail descente relâchée, foulée courte sous le corps, ne pas freiner",
    "km": 14,
    "dp": 500,
    "note": "Technique descente : regard loin, appuis souples"
  },
  {
    "id": "s-T-2026-04-26",
    "phase": 2,
    "week": 5,
    "date": "2026-04-26",
    "day": "Dim",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-04-27",
    "phase": 2,
    "week": 6,
    "weekLabel": "27 avr – 3 mai",
    "date": "2026-04-27",
    "day": "Lun",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-04-28",
    "phase": 2,
    "week": 6,
    "date": "2026-04-28",
    "day": "Mar",
    "type": "EF",
    "content": "Ech 10'@5:45/km | Footing EF route 40'@5:45/km | RAC 10'@5:45/km",
    "km": 10,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-04-29",
    "phase": 2,
    "week": 6,
    "date": "2026-04-29",
    "day": "Mer",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-04-30",
    "phase": 2,
    "week": 6,
    "date": "2026-04-30",
    "day": "Jeu",
    "type": "VMA",
    "content": "Ech 15'@5:45/km + 4 strides 80m@4:05/km | 6x2'@4:05/km — recup 2'@5:45/km | RAC 10'@5:45/km",
    "km": 9,
    "dp": null,
    "note": "Première VMA — partir prudemment sur les 2 premiers intervals"
  },
  {
    "id": "s-T-2026-05-01",
    "phase": 2,
    "week": 6,
    "date": "2026-05-01",
    "day": "Ven",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": "Férié"
  },
  {
    "id": "s-T-2026-05-02",
    "phase": 2,
    "week": 6,
    "date": "2026-05-02",
    "day": "Sam",
    "type": "TRAIL",
    "content": "Ech 10' marche | Sortie trail longue 1h45 — simulation effort course : monter en marchant, courir le plat et descente | RAC 10' marche",
    "km": 16,
    "dp": 600,
    "note": "Alimentation toutes les 45min — tester ce qui passe bien"
  },
  {
    "id": "s-T-2026-05-03",
    "phase": 2,
    "week": 6,
    "date": "2026-05-03",
    "day": "Dim",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-05-04",
    "phase": 2,
    "week": 7,
    "weekLabel": "4 – 7 mai",
    "date": "2026-05-04",
    "day": "Lun",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-05-05",
    "phase": 2,
    "week": 7,
    "date": "2026-05-05",
    "day": "Mar",
    "type": "EF",
    "content": "Ech 10'@5:45/km | Footing route léger 30'@5:45/km | RAC 10'@5:45/km",
    "km": 8,
    "dp": null,
    "note": "Semaine courte — garder les jambes"
  },
  {
    "id": "s-T-2026-05-06",
    "phase": 2,
    "week": 7,
    "date": "2026-05-06",
    "day": "Mer",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-05-07",
    "phase": 2,
    "week": 7,
    "date": "2026-05-07",
    "day": "Jeu",
    "type": "TEMPO",
    "content": "Ech 15'@5:45/km | 2x12'@4:45/km — recup 3'@5:45/km | RAC 10'@5:45/km",
    "km": 10,
    "dp": null,
    "note": "Dernière séance qualité avant WC — rester dans les allures"
  },
  {
    "id": "s-T-2026-05-08",
    "phase": 3,
    "phaseLabel": "WC Mai + consolidation",
    "week": 8,
    "weekLabel": "WC Mai 8–10 mai",
    "date": "2026-05-08",
    "day": "Ven",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-05-09",
    "phase": 3,
    "week": 8,
    "date": "2026-05-09",
    "day": "Sam",
    "type": "WC",
    "content": "Ech 10' marche | 🏔 WC Trail J1 — 14–16km / 700D+ — EF strict, marcher toutes les montées, découvrir le terrain | RAC 10' marche",
    "km": 16,
    "dp": 700,
    "note": "EF strict. Alimentation 1×/h. Ne pas partir avec les autres.",
    "isEvent": true
  },
  {
    "id": "s-T-2026-05-10",
    "phase": 3,
    "week": 8,
    "date": "2026-05-10",
    "day": "Dim",
    "type": "WC",
    "content": "Ech 10' marche | 🏔 WC Trail J2 — 10–12km / 500D+ — sortie récup, travailler descente relâchée | RAC 10' marche",
    "km": 12,
    "dp": 500,
    "note": "Moins d'intensité — travail technique descente"
  },
  {
    "id": "s-T-2026-05-11",
    "phase": 3,
    "week": 9,
    "weekLabel": "11 – 17 mai",
    "date": "2026-05-11",
    "day": "Lun",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-05-12",
    "phase": 3,
    "week": 9,
    "date": "2026-05-12",
    "day": "Mar",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": "Récup WC"
  },
  {
    "id": "s-T-2026-05-13",
    "phase": 3,
    "week": 9,
    "date": "2026-05-13",
    "day": "Mer",
    "type": "EF",
    "content": "Ech 10'@5:45/km | Footing récup route 30'@5:45/km | RAC 10'@5:45/km",
    "km": 8,
    "dp": null,
    "note": "Si jambes lourdes : repos"
  },
  {
    "id": "s-T-2026-05-14",
    "phase": 3,
    "week": 9,
    "date": "2026-05-14",
    "day": "Jeu",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-05-15",
    "phase": 3,
    "week": 9,
    "date": "2026-05-15",
    "day": "Ven",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-05-16",
    "phase": 3,
    "week": 9,
    "date": "2026-05-16",
    "day": "Sam",
    "type": "TRAIL",
    "content": "Ech 10' marche | Trail EF 1h — relance post-WC, terrain varié, allure confortable | RAC 10' marche",
    "km": 12,
    "dp": 400,
    "note": ""
  },
  {
    "id": "s-T-2026-05-17",
    "phase": 3,
    "week": 9,
    "date": "2026-05-17",
    "day": "Dim",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-05-18",
    "phase": 3,
    "week": 10,
    "weekLabel": "18 – 24 mai",
    "date": "2026-05-18",
    "day": "Lun",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-05-19",
    "phase": 3,
    "week": 10,
    "date": "2026-05-19",
    "day": "Mar",
    "type": "VMA",
    "content": "Ech 15'@5:45/km + 4 strides 80m@4:05/km | 7x2'@4:05/km — recup 2'@5:45/km | RAC 10'@5:45/km",
    "km": 10,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-05-20",
    "phase": 3,
    "week": 10,
    "date": "2026-05-20",
    "day": "Mer",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-05-21",
    "phase": 3,
    "week": 10,
    "date": "2026-05-21",
    "day": "Jeu",
    "type": "EF",
    "content": "Ech 10'@5:45/km | Footing route 45'@5:45/km | RAC 10'@5:45/km",
    "km": 11,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-05-22",
    "phase": 3,
    "week": 10,
    "date": "2026-05-22",
    "day": "Ven",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-05-23",
    "phase": 3,
    "week": 10,
    "date": "2026-05-23",
    "day": "Sam",
    "type": "TRAIL",
    "content": "Ech 10' marche | Trail 1h45 — simulation course 18km : allure EF en montée, courir le plat et descente | RAC 10' marche",
    "km": 17,
    "dp": 700,
    "note": "Simulation la plus proche de la course — tester équipement et chaussures"
  },
  {
    "id": "s-T-2026-05-24",
    "phase": 3,
    "week": 10,
    "date": "2026-05-24",
    "day": "Dim",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-05-25",
    "phase": 3,
    "week": 11,
    "weekLabel": "25 – 31 mai",
    "date": "2026-05-25",
    "day": "Lun",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-05-26",
    "phase": 3,
    "week": 11,
    "date": "2026-05-26",
    "day": "Mar",
    "type": "TEMPO",
    "content": "Ech 15'@5:45/km | 2x15'@4:45/km — recup 4'@5:45/km | RAC 10'@5:45/km",
    "km": 11,
    "dp": null,
    "note": "Bloc tempo le plus long du plan"
  },
  {
    "id": "s-T-2026-05-27",
    "phase": 3,
    "week": 11,
    "date": "2026-05-27",
    "day": "Mer",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-05-28",
    "phase": 3,
    "week": 11,
    "date": "2026-05-28",
    "day": "Jeu",
    "type": "EF",
    "content": "Ech 10'@5:45/km | Footing route 40'@5:45/km | RAC 10'@5:45/km",
    "km": 10,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-05-29",
    "phase": 3,
    "week": 11,
    "date": "2026-05-29",
    "day": "Ven",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-05-30",
    "phase": 3,
    "week": 11,
    "date": "2026-05-30",
    "day": "Sam",
    "type": "TRAIL",
    "content": "Ech 10' marche | Trail 1h30 — terrain technique, travailler les transitions montée/descente, allure course | RAC 10' marche",
    "km": 15,
    "dp": 600,
    "note": ""
  },
  {
    "id": "s-T-2026-05-31",
    "phase": 3,
    "week": 11,
    "date": "2026-05-31",
    "day": "Dim",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-06-01",
    "phase": 4,
    "phaseLabel": "Affûtage final — Fraîcheur maximale",
    "week": 12,
    "weekLabel": "1 – 7 juin",
    "date": "2026-06-01",
    "day": "Lun",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-06-02",
    "phase": 4,
    "week": 12,
    "date": "2026-06-02",
    "day": "Mar",
    "type": "VMA",
    "content": "Ech 15'@5:45/km + 4 strides 80m@4:05/km | 5x2'@4:05/km — recup 2'@5:45/km | RAC 10'@5:45/km",
    "km": 9,
    "dp": null,
    "note": "Volume réduit — garder la piqûre"
  },
  {
    "id": "s-T-2026-06-03",
    "phase": 4,
    "week": 12,
    "date": "2026-06-03",
    "day": "Mer",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-06-04",
    "phase": 4,
    "week": 12,
    "date": "2026-06-04",
    "day": "Jeu",
    "type": "EF",
    "content": "Ech 10'@5:45/km | Footing route 35'@5:45/km | RAC 10'@5:45/km",
    "km": 9,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-06-05",
    "phase": 4,
    "week": 12,
    "date": "2026-06-05",
    "day": "Ven",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-06-06",
    "phase": 4,
    "week": 12,
    "date": "2026-06-06",
    "day": "Sam",
    "type": "TRAIL",
    "content": "Ech 10' marche | Trail 1h — terrain similaire course, allure race day, pas d'effort max | RAC 10' marche",
    "km": 11,
    "dp": 400,
    "note": "Dernière sortie longue — tester le matériel définitif"
  },
  {
    "id": "s-T-2026-06-07",
    "phase": 4,
    "week": 12,
    "date": "2026-06-07",
    "day": "Dim",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-06-08",
    "phase": 4,
    "week": 13,
    "weekLabel": "8 – 14 juin",
    "date": "2026-06-08",
    "day": "Lun",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-06-09",
    "phase": 4,
    "week": 13,
    "date": "2026-06-09",
    "day": "Mar",
    "type": "TEMPO",
    "content": "Ech 15'@5:45/km | 2x10'@4:45/km — recup 3'@5:45/km | RAC 10'@5:45/km",
    "km": 9,
    "dp": null,
    "note": "Dernière séance qualité"
  },
  {
    "id": "s-T-2026-06-10",
    "phase": 4,
    "week": 13,
    "date": "2026-06-10",
    "day": "Mer",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-06-11",
    "phase": 4,
    "week": 13,
    "date": "2026-06-11",
    "day": "Jeu",
    "type": "EF",
    "content": "Ech 10'@5:45/km | Footing route 25' + 4 strides 100m@4:05/km | RAC 10'@5:45/km",
    "km": 8,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-06-12",
    "phase": 4,
    "week": 13,
    "date": "2026-06-12",
    "day": "Ven",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-06-13",
    "phase": 4,
    "week": 13,
    "date": "2026-06-13",
    "day": "Sam",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-06-14",
    "phase": 4,
    "week": 13,
    "date": "2026-06-14",
    "day": "Dim",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-06-15",
    "phase": 4,
    "week": 14,
    "weekLabel": "15 – 21 juin",
    "date": "2026-06-15",
    "day": "Lun",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-06-16",
    "phase": 4,
    "week": 14,
    "date": "2026-06-16",
    "day": "Mar",
    "type": "EF",
    "content": "Ech 10'@5:45/km | Footing route 20'@5:45/km + 3 strides 80m@4:05/km | RAC 10'@5:45/km",
    "km": 6,
    "dp": null,
    "note": "Activation légère — jambes légères"
  },
  {
    "id": "s-T-2026-06-17",
    "phase": 4,
    "week": 14,
    "date": "2026-06-17",
    "day": "Mer",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-06-18",
    "phase": 4,
    "week": 14,
    "date": "2026-06-18",
    "day": "Jeu",
    "type": "EF",
    "content": "Footing route 15' très léger@5:45/km — juste bouger, pas d'objectif",
    "km": 3,
    "dp": null,
    "note": ""
  },
  {
    "id": "s-T-2026-06-19",
    "phase": 4,
    "week": 14,
    "date": "2026-06-19",
    "day": "Ven",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": "Repos total — nutrition, hydratation, sommeil"
  },
  {
    "id": "s-T-2026-06-20",
    "phase": 4,
    "week": 14,
    "date": "2026-06-20",
    "day": "Sam",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": "Veille course — préparer dossard, matériel, petit-déj testé"
  },
  {
    "id": "s-T-2026-06-21",
    "phase": 4,
    "week": 14,
    "date": "2026-06-21",
    "day": "Dim",
    "type": "RACE",
    "content": "Ech 15'@5:45/km + 3 strides 100m | 🏆 18km / 1000D+ — départ contrôlé, marcher toutes les montées >10%, courir plat et descente@4:25/km | RAC 15' marche@5:45/km",
    "km": 18,
    "dp": 1000,
    "note": "🏆 OBJECTIF — allure cible 6:00–6:30/km GAP. Gel/barre toutes les 45min.",
    "isEvent": true
  },
  {
    "id": "s-T-2026-06-22",
    "phase": 4,
    "week": 14,
    "date": "2026-06-22",
    "day": "Lun",
    "type": "REPOS",
    "content": "",
    "km": null,
    "dp": null,
    "note": "Récup post-course 🎉"
  }
]
